grails-app/domain/com/youniversity/core/app/FavouriteApp.groovy
package com.youniversity.core.app
import com.youniversity.core.user.User

class FavouriteApp {
    Application application
    boolean widget
    User user

    static constraints = {
    }

    static mapping = {
        user nullable:false
        application lazy: false
    }
}

grails-app/controllers/com/youniversity/core/app/FavouriteAppController.groovy
package com.youniversity.core.app

import grails.transaction.*
import com.youniversity.core.user.User

import static org.springframework.http.HttpStatus.*

@Transactional(readOnly = true)
class FavouriteAppController {

    def permissions =[
            "/favourite-app/index":["configAttribute":"ROLE_USER_MEMBER"],
            "/favourite-app/create":["configAttribute":"ROLE_USER_MEMBER"],
            "/favourite-app/save/**":["configAttribute":"ROLE_USER_MEMBER",
                    "authMethod":[
                            "ROLE_USER_MEMBER":"true"
                    ]
            ],
            "/favourite-app/edit":["configAttribute":"ROLE_USER_MEMBER"],
            "/favourite-app/update/**":["configAttribute":"ROLE_USER_MEMBER",
                    "authMethod":[
                            "ROLE_USER_MEMBER":"true"
                    ]
            ],
            "/favourite-app/delete/**":["configAttribute":"ROLE_USER_MEMBER",
                    "authMethod":[
                            "ROLE_USER_MEMBER":"true"
                    ]
            ],
            "/favourite-app/show/**":["configAttribute":"ROLE_USER_MEMBER",
                    "authMethod":[
                            "ROLE_USER_MEMBER":"true"
                    ]
            ],
            "/favourite-app/list":["configAttribute":"ROLE_USER_MEMBER"],
            "/favourite-app/add/**":["configAttribute":"ROLE_USER_MEMBER",
                    "authMethod":[
                            "ROLE_USER_MEMBER":"true"
                    ]
            ],
            "/favourite-app/add-widget/**":["configAttribute":"ROLE_USER_MEMBER",
                    "authMethod":[
                            "ROLE_USER_MEMBER":"true"
                    ]
            ],
            "/favourite-app/remove/**":["configAttribute":"ROLE_USER_MEMBER",
                    "authMethod":[
                            "ROLE_USER_MEMBER":"true"
                    ]
            ],
            "/favourite-app/remove-widget/**":["configAttribute":"ROLE_USER_MEMBER",
                    "authMethod":[
                            "ROLE_USER_MEMBER":"true"
                    ]
            ]
    ]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond FavouriteApp.list(params), model:[favouriteAppInstanceCount: FavouriteApp.count()]
    }

    def show(FavouriteApp favouriteAppInstance) {
        respond favouriteAppInstance
    }

    def create() {
        respond new FavouriteApp(params)
    }

    @Transactional
    def add(Integer id) {
        Application app = Application.findById(id)
        new FavouriteApp(application: app, user: User.get(1), widget:false).save()
        redirect controller: "Application", action: "index"
    }

    @Transactional
    def addWidget(Integer id) {
        Application app = Application.findById(id)
        new FavouriteApp(application: app, user: User.get(1), widget:true).save()
        redirect controller: "Application", action: "index"
    }

    @Transactional
    def remove(Integer id)  {
        Application app = Application.findById(id)
        User user = User.findById(1)
        FavouriteApp fav = FavouriteApp.findByApplicationAndUserAndWidget(app,user,false)
        fav.delete(flush:true)
        redirect controller: "Application", action: "index"
    }

    @Transactional
    def removeWidget(Integer id)  {
        Application app = Application.findById(id)
        User user = User.findById(1)
        FavouriteApp fav = FavouriteApp.findByApplicationAndUserAndWidget(app,user,true)
        fav.delete(flush:true)
        redirect controller: "Application", action: "index"
    }

    @Transactional
    def save(FavouriteApp favouriteAppInstance) {
        if(favouriteAppInstance.hasErrors()) {
            respond favouriteAppInstance.errors, view:'create'
        }
        else {
            favouriteAppInstance.save flush:true
            request.withFormat {
                form { 
                    flash.message = message(code: 'default.created.message', args: [message(code: 'favouriteAppInstance.label', default: 'FavouriteApp'), favouriteAppInstance.id])
                    redirect favouriteAppInstance
                }
                '*' { respond favouriteAppInstance, [status: CREATED] }
            }
        }
    }


    def edit(FavouriteApp favouriteAppInstance) { 
        respond favouriteAppInstance  
    }

    @Transactional
    def update(FavouriteApp favouriteAppInstance) {
        if(favouriteAppInstance == null) {
            render status:404
        }
        else if(favouriteAppInstance.hasErrors()) {
            respond favouriteAppInstance.errors, view:'edit'
        }
        else {
            favouriteAppInstance.save flush:true
            request.withFormat {
                form { 
                    flash.message = message(code: 'default.updated.message', args: [message(code: 'FavouriteApp.label', default: 'FavouriteApp'), favouriteAppInstance.id])
                    redirect favouriteAppInstance 
                }
                '*'{ respond favouriteAppInstance, [status: OK] }
            }
        }        
    }

    @Transactional
    def delete(FavouriteApp favouriteAppInstance) {
        if(favouriteAppInstance) {
            favouriteAppInstance.delete flush:true
            request.withFormat {
                form { 
                    flash.message = message(code: 'default.deleted.message', args: [message(code: 'FavouriteApp.label', default: 'FavouriteApp'), favouriteAppInstance.id])
                    redirect action:"index", method:"GET" 
                }
                '*'{ render status: NO_CONTENT }
            }                
        }
        else {
            render status: NOT_FOUND
        }
    }
}

grails-app/views/favouriteApp/_form.gsp
<%@ page import="com.youniversity.core.app.FavouriteApp" %>



<div class="fieldcontain ${hasErrors(bean: favouriteAppInstance, field: 'application', 'error')} required">
	<label for="application">
		<g:message code="favouriteApp.application.label" default="Application" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="application" name="application.id" from="${com.youniversity.core.app.Application.list()}" optionKey="id" required="" value="${favouriteAppInstance?.application?.id}" class="many-to-one"/>
</div>

<div class="fieldcontain ${hasErrors(bean: favouriteAppInstance, field: 'users', 'error')} ">
	<label for="users">
		<g:message code="favouriteApp.users.label" default="Users" />
		
	</label>
	
</div>

<div class="fieldcontain ${hasErrors(bean: favouriteAppInstance, field: 'widget', 'error')} ">
	<label for="widget">
		<g:message code="favouriteApp.widget.label" default="Widget" />
		
	</label>
	<g:checkBox name="widget" value="${favouriteAppInstance?.widget}" />
</div>

grails-app/views/favouriteApp/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'favouriteApp.label', default: 'FavouriteApp')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-favouriteApp" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-favouriteApp" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${favouriteAppInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${favouriteAppInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:favouriteAppInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/favouriteApp/edit.gsp
<%@ page import="com.youniversity.core.app.FavouriteApp" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'favouriteApp.label', default: 'FavouriteApp')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-favouriteApp" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-favouriteApp" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${favouriteAppInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${favouriteAppInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:favouriteAppInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${favouriteAppInstance?.version}" />				
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/favouriteApp/index.gsp
<%@ page import="com.youniversity.core.app.FavouriteApp" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'favouriteApp.label', default: 'FavouriteApp')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-favouriteApp" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-favouriteApp" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<th><g:message code="favouriteApp.application.label" default="Application" /></th>
					
						<g:sortableColumn property="widget" title="${message(code: 'favouriteApp.widget.label', default: 'Widget')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${favouriteAppInstanceList}" status="i" var="favouriteAppInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${favouriteAppInstance.id}">${fieldValue(bean: favouriteAppInstance, field: "application")}</g:link></td>
					
						<td><g:formatBoolean boolean="${favouriteAppInstance.widget}" /></td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${favouriteAppInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/favouriteApp/show.gsp
<%@ page import="com.youniversity.core.app.FavouriteApp" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'favouriteApp.label', default: 'FavouriteApp')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-favouriteApp" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-favouriteApp" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list favouriteApp">
			
				<g:if test="${favouriteAppInstance?.application}">
				<li class="fieldcontain">
					<span id="application-label" class="property-label"><g:message code="favouriteApp.application.label" default="Application" /></span>
					
						<span class="property-value" aria-labelledby="application-label"><g:link controller="application" action="show" id="${favouriteAppInstance?.application?.id}">${favouriteAppInstance?.application?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
				<g:if test="${favouriteAppInstance?.users}">
				<li class="fieldcontain">
					<span id="users-label" class="property-label"><g:message code="favouriteApp.users.label" default="Users" /></span>
					
						<g:each in="${favouriteAppInstance.users}" var="u">
						<span class="property-value" aria-labelledby="users-label"><g:link controller="user" action="show" id="${u.id}">${u?.encodeAsHTML()}</g:link></span>
						</g:each>
					
				</li>
				</g:if>
			
				<g:if test="${favouriteAppInstance?.widget}">
				<li class="fieldcontain">
					<span id="widget-label" class="property-label"><g:message code="favouriteApp.widget.label" default="Widget" /></span>
					
						<span class="property-value" aria-labelledby="widget-label"><g:formatBoolean boolean="${favouriteAppInstance?.widget}" /></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:favouriteAppInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${favouriteAppInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>